# 车牌识别相关
provinces: [ "皖", "沪", "津", "渝", "冀", "晋", "蒙", "辽", "吉", "黑", "苏", "浙", "京", "闽", "赣", "鲁", "豫", "鄂", "湘", "粤", "桂", "琼", "川", "贵", "云", "藏", "陕", "甘", "青", "宁", "新", "警", "学", "O" ]
alphabets: [ 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'J', 'K', 'L', 'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W',
             'X', 'Y', 'Z', 'O' ]
ads: [ 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'J', 'K', 'L', 'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X',
       'Y', 'Z', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'O' ]

# 调试配置
debug: False

# 数据路径配置
data_paths:
    raw: "data/raw"      # 原始数据根目录
    yolo: "data/yolo"    # YOLO格式数据集目录


# 模型配置
model:
  detector:
    pretrained: yolov8n.yaml
    freeze_backbone: True
  recognizer:
    input_size: 128
    lstm_units: 256

# 数据处理高级选项
data_processing:
    max_workers: 4      # 并行处理线程数
    validation_split: 0.2
    test_split: 0.1
    
# 训练参数
training:
    epochs: 100
    batch_size: 16
    patience: 10  # 早停轮次
    optimizer: Adam
    lr: 0.001
    weight_decay: 0.0005
    validation_split: 0.2

# 优化器
optim:
  det_lr: 0.001
  recog_lr: 0.01
  weight_decay: 0.0005

# 损失权重
loss:
  recog_weight: 0.8